IMPORTING THE DATASET

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\vanam\Downloads\pokedex.csv")
print("DataSet info: ")
df.info()

DataSet info: 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   id         1025 non-null   int64 
 1   name       1025 non-null   object
 2   height     1025 non-null   int64 
 3   weight     1025 non-null   int64 
 4   hp         1025 non-null   int64 
 5   attack     1025 non-null   int64 
 6   defense    1025 non-null   int64 
 7   s_attack   1025 non-null   int64 
 8   s_defense  1025 non-null   int64 
 9   speed      1025 non-null   int64 
 10  type       1025 non-null   object
 11  evo_set    1025 non-null   int64 
 12  info       1025 non-null   object
dtypes: int64(10), object(3)
memory usage: 104.2+ KB


## PERFORMING OPERATIONS -- 

### NUMPY OPERATIONS:
1. Creating arrays
2. Array indexing and slicing
3. Reshaping arrays
4. Concatenation and splitting
5. Universal Functions (Ufuncs)
6. Aggregations
7. Broadcasting
8. Boolean Masks and Fancy Indexing
9. Sorting 
10. Structured arrays

In [3]:
import numpy as np

#Creating a new numpy array
attack_array = np.array(df["attack"])

#Converting a column to a numpy array
hp_array = np.array(df["hp"])



print(hp_array)
print(attack_array)

[45 60 80 ... 90 90 88]
[49 62 82 ... 72 65 88]


In [4]:
#Getting first 10 Pokemon HP values
print(hp_array[:10])

#Getting last 5 Attack values
print(attack_array[-5:])

[45 60 80 39 58 78 44 59 79 45]
[ 73 120  72  65  88]


In [5]:
#Reshape the first 20 HP values into a 4x5 matrix
hp_reshaped = hp_array[:20].reshape(4, 5)
print(hp_reshaped)


[[45 60 80 39 58]
 [78 44 59 79 45]
 [50 60 40 45 65]
 [40 63 83 30 55]]


In [6]:
#Concatenation
concat_array = np.concatenate((hp_array[:10], attack_array[:10]))
#Splitting
split_hp = np.split(hp_array[:10], 2)

print(concat_array)
print(split_hp)


[45 60 80 39 58 78 44 59 79 45 49 62 82 52 64 84 48 63 83 30]
[array([45, 60, 80, 39, 58], dtype=int64), array([78, 44, 59, 79, 45], dtype=int64)]


In [7]:
hp_array = np.array(df["hp"])
attack_array = np.array(df["attack"])
speed_array = np.array(df["speed"])

# Square root of all attack values
print("Square root function:")
print(np.sqrt(attack_array))

# Multiply Attack by 2
print("\nMultiplication function:")
print(np.multiply(attack_array, 2))

# Divide Speed by 2
print("\nDivision function:")
print(np.divide(speed_array, 2))

# Exponential of HP values (e^x)
print("\nExponential function:")
print(np.exp(hp_array))

# Logarithm of Attack values (Natural log)
print("\n Logarithemic function:")
print(np.log(attack_array + 1))  # Adding 1 to avoid log(0)

# Convert Speed to Radians and Compute Sine
print("\n sin function:")
print(np.sin(np.radians(speed_array)))

# Cosine of Attack values
print("\n cos function:")
print(np.cos(np.radians(attack_array)))

# Absolute values (if any negative values exist)
print("\n absolute function")
print(np.abs(hp_array))

# Rounding Attack values to nearest integer
print("\n rounding function")
print(np.round(attack_array))

# Check which pokemon have HP greater than 300
print("\n greater than operator")
print(np.greater(hp_array, 300))

# Check which pokemon have HP less than 100
print("\n less than operator")
print(np.less(hp_array, 100))

# Find pokemon with exactly 50 Speed
print("\n equals operator")
print(np.equal(speed_array, 50))



Square root function:
[7.         7.87400787 9.05538514 ... 8.48528137 8.06225775 9.38083152]

Multiplication function:
[ 98 124 164 ... 144 130 176]

Division function:
[22.5 30.  40.  ... 49.  30.  44. ]

Exponential function:
[3.49342711e+19 1.14200739e+26 5.54062238e+34 ... 1.22040329e+39
 1.22040329e+39 1.65163625e+38]

 Logarithemic function:
[3.91202301 4.14313473 4.41884061 ... 4.29045944 4.18965474 4.48863637]

 sin function:
[0.70710678 0.8660254  0.98480775 ... 0.99026807 0.8660254  0.99939083]

 cos function:
[0.65605903 0.46947156 0.1391731  ... 0.30901699 0.42261826 0.0348995 ]

 absolute function
[45 60 80 ... 90 90 88]

 rounding function
[49 62 82 ... 72 65 88]

 greater than operator
[False False False ... False False False]

 less than operator
[ True  True  True ...  True  True  True]

 equals operator
[False False False ... False False False]


In [8]:
hp_array = np.array(df["hp"])
attack_array = np.array(df["attack"])
speed_array = np.array(df["speed"])

# Sum aggregation
total_hp = np.sum(hp_array)

# Mean (Average)
mean_attack = np.mean(attack_array)

# Median
median_speed = np.median(speed_array) 

# Standard Deviation
std_hp = np.std(hp_array) 

# Variance
var_attack = np.var(attack_array) 

# Minimum and Maximum
min_speed = np.min(speed_array)
max_speed = np.max(speed_array)  
print("\ntotal hp", total_hp)
print("\nmean attack: ", mean_attack)
print("\nmedian speed: ", median_speed)
print("\nStandard Deviation in HP: ", std_hp)
print("\nVariance in attack: ", var_attack)
print("\nLowest speed: ", min_speed)
print("\nHighest speed: ", max_speed)

# Cumulative Sum
print("\ncumulative sum of HP: ")
print(np.cumsum(hp_array))  # Running total of HP





total hp 71939

mean attack:  77.52195121951219

median speed:  65.0

Standard Deviation in HP:  26.61806007561733

Variance in attack:  886.1343961927424

Lowest speed:  5

Highest speed:  200

cumulative sum of HP: 
[   45   105   185 ... 71761 71851 71939]


In [9]:
# Sorting pokemon by Speed
df_sorted_speed = df.sort_values("speed", ascending=False)
print(df_sorted_speed)


      id        name  height  weight   hp  attack  defense  s_attack  \
893  894   regieleki      12    1450   80     100       50       100   
290  291     ninjask       8     120   61      90       45        50   
794  795   pheromosa      18     250   71     137       37       137   
100  101   electrode      12     666   60      50       70        80   
385  386      deoxys      17     608   50     150       50       150   
..   ...         ...     ...     ...  ...     ...      ...       ...   
998  999  gimmighoul       3      50   45      30       70        75   
828  829  gossifleur       4      22   40      40       60        40   
445  446    munchlax       6    1050  135      85       40        40   
212  213     shuckle       6     205   20      10      230        10   
770  771   pyukumuku       3      12   55      60      130        30   

     s_defense  speed            type  evo_set  \
893         50    200      {electric}      472   
290         50    160    {bug,flyin

In [10]:
speed_array = np.array(df["speed"])
attack_array = np.array(df["attack"])

# Get the indices of sorted Attack values
sorted_indices = np.argsort(attack_array)
print(sorted_indices)

# Partition at index 5 (Top 5 fastest pokemon)
top_5_fastest = np.partition(speed_array, -5)[-5:]
print(top_5_fastest)


[112 439 128 ... 288 408 797]
[150 150 151 160 200]


In [11]:
#Broadcasting: 
#Increase all attack values by 5
attack_array += 5
print(attack_array)

[54 67 87 ... 77 70 93]


In [12]:
#Boolean Masking: 
#Get pokemon with HP greater than 100
high_hp_pokemon = df[df["hp"] > 100]
print(high_hp_pokemon)


        id          name  height  weight   hp  attack  defense  s_attack  \
38      39    jigglypuff       5      55  115      45       20        45   
39      40    wigglytuff      10     120  140      70       45        85   
88      89           muk      12     300  105     105       75        65   
111    112        rhydon      19    1200  105     130      120        45   
112    113       chansey      11     346  250       5        5        35   
...    ...           ...     ...     ...  ...     ...      ...       ...   
1002  1003       ting-lu      27    6997  155     110      125        55   
1004  1005  roaring-moon      20    3800  105     139       71        55   
1018  1019     hydrapple      18     930  106      80      110       120   
1019  1020  gouging-fire      35    5900  105     115      121        65   
1020  1021   raging-bolt      52    4800  125      73       91       137   

      s_defense  speed               type  evo_set  \
38           25     20     {norma

In [39]:
# Fancy Indexing:
#Select specific pokemon IDs
selected_pokemon = df.iloc[[0, 5, 10]]
print(selected_pokemon)

    id       name  height  weight  hp  attack  defense  s_attack  s_defense  \
0    1  bulbasaur       7      69  45      49       49        65         65   
5    6  charizard      17     905  78      84       78       109         85   
10  11    metapod       7      99  50      20       55        25         25   

    speed            type  evo_set  \
0      45  {grass,poison}        1   
5     100   {fire,flying}        2   
10     30           {bug}        4   

                                                 info  attack_boosted  \
0   A strange seed was planted on its back at birt...              59   
5   Spits fire that is hot enough to melt boulders...              94   
10  This POKéMON is vulnerable to attack while its...              30   

    speed_halved  attack_modified  speed_rank  total_stats  speed_modified  \
0           22.5             49.0       748.0          188            45.0   
5           50.0             84.0       128.0          340           150.0   
10 

In [14]:
import numpy as np

#Structured Array: 
structured_array = np.array(
    list(zip(df["id"], df["name"], df["hp"])),
    dtype=[("ID", "i4"), ("Name", "U20"), ("HP", "i4")]
)
print(structured_array)

[(   1, 'bulbasaur', 45) (   2, 'ivysaur', 60) (   3, 'venusaur', 80) ...
 (1023, 'iron-crown', 90) (1024, 'terapagos', 90) (1025, 'pecharunt', 88)]


## Pandas Operations: 
1. Pandas Series
2. Pandas DataFrame
3. Indexing and Selecting
4. Index Alignment and Operations
5. Handling Missing data
6. Heirarchial Indexing 

In [15]:
# Create Series from HP column
hp_series = pd.Series(df["hp"])
print("\n",hp_series)



 0        45
1        60
2        80
3        39
4        58
       ... 
1020    125
1021     90
1022     90
1023     90
1024     88
Name: hp, Length: 1025, dtype: int64


In [16]:
# Arithmetic Operations
df["attack_boosted"] = df["attack"] + 10
df["speed_halved"] = df["speed"] / 2

# Conditional Operations
strong_pokemon = df[df["attack"] > 100]
fast_pokemon = df[df["speed"] > 80]

# Apply a function to each value
df["attack_modified"] = df["attack"].apply(lambda x: x * 1.2 if x > 100 else x)


In [17]:
# operations on series
print(df["attack"].sum())  # Total Attack
print(df["speed"].mean())  # Average Speed
print(df["hp"].min())      # Minimum HP
print(df["defense"].max()) # Maximum Defense
print(df["type"].value_counts())  # Count pokemon per Type


79460
67.18634146341464
1
230
type
{normal}          75
{water}           74
{grass}           47
{psychic}         39
{fire}            36
                  ..
{flying,water}     1
{poison,bug}       1
{dark,normal}      1
{ghost,dark}       1
{poison,ghost}     1
Name: count, Length: 203, dtype: int64


In [18]:
# Sort pokemon by Attack (Descending)
sorted_attack = df["attack"].sort_values(ascending=False)

# Rank pokemon based on Speed
df["speed_rank"] = df["speed"].rank(method="min", ascending=False)
print(df["speed_rank"])


0       748.0
1       554.0
2       321.0
3       489.0
4       321.0
        ...  
1020    373.0
1021     30.0
1022    159.0
1023    554.0
1024    257.0
Name: speed_rank, Length: 1025, dtype: float64


In [19]:
# Fill missing values in Attack with the average
df.update(df[["attack"]].fillna(df["attack"].mean()))


# Drop rows with missing Speed values
df.dropna(subset=["speed"], inplace=True)


In [20]:
#DATAFRAME - Operations 
# Create a subset DataFrame
subset_df = df[["name", "type", "hp"]]
print("\n",subset_df)


               name               type   hp
0        bulbasaur     {grass,poison}   45
1          ivysaur     {grass,poison}   60
2         venusaur     {grass,poison}   80
3       charmander             {fire}   39
4       charmeleon             {fire}   58
...            ...                ...  ...
1020   raging-bolt  {electric,dragon}  125
1021  iron-boulder     {rock,psychic}   90
1022    iron-crown    {steel,psychic}   90
1023     terapagos           {normal}   90
1024     pecharunt     {poison,ghost}   88

[1025 rows x 3 columns]


In [21]:
# Select multiple columns
df_subset = df[["name", "attack", "speed"]]

# Select rows where Attack > 100
strong_pokemon = df[df["attack"] > 100]
print(strong_pokemon)

# Select rows using index
first_five = df.iloc[:5]  # First 5 rows
last_three = df.iloc[-3:]  # Last 3 rows
print(first_five, last_three)


        id          name  height  weight   hp  attack  defense  s_attack  \
33      34      nidoking      14     620   81     102       77        85   
56      57      primeape      10     320   65     105       60        60   
58      59      arcanine      19    1550   90     110       80       100   
67      68       machamp      16    1300   90     130       80        65   
70      71    victreebel      17     155   80     105       65       100   
...    ...           ...     ...     ...  ...     ...      ...       ...   
1013  1014       okidogi      18     922   88     128      115        58   
1016  1017       ogerpon      12     398   80     120       84        60   
1017  1018    archaludon      20     600   90     105      130       125   
1019  1020  gouging-fire      35    5900  105     115      121        65   
1021  1022  iron-boulder      15    1625   90     120       80        68   

      s_defense  speed               type  evo_set  \
33           75     85    {poison

In [22]:
# Create a new column (Total Stats)
df["total_stats"] = df["attack"] + df["defense"] + df["speed"] + df["hp"]

# Multiply entire DataFrame by 2 (only numeric columns)
df_numeric = df.select_dtypes(include="number")
df_doubled = df_numeric * 2
print(df_numeric, df_doubled)


        id  height  weight   hp  attack  defense  s_attack  s_defense  speed  \
0        1       7      69   45      49       49        65         65     45   
1        2      10     130   60      62       63        80         80     60   
2        3      20    1000   80      82       83       100        100     80   
3        4       6      85   39      52       43        60         50     65   
4        5      11     190   58      64       58        80         65     80   
...    ...     ...     ...  ...     ...      ...       ...        ...    ...   
1020  1021      52    4800  125      73       91       137         89     75   
1021  1022      15    1625   90     120       80        68        108    124   
1022  1023      16    1560   90      72      100       122        108     98   
1023  1024       2      65   90      65       85        65         85     60   
1024  1025       3       3   88      88      160        88         88     88   

      evo_set  attack_boosted  speed_ha

In [23]:
# Group pokemon by Type and get Average Attack
type_attack = df.groupby("type")["attack"].mean()
print(type_attack)

# Get Maximum Speed per Type
type_speed = df.groupby("type")["speed"].max()
print(type_speed)

type
{bug,dark}         102.000000
{bug,electric}      69.000000
{bug,fairy}         50.000000
{bug,fighting}     134.000000
{bug,fire}          72.500000
                      ...    
{water,poison}      68.333333
{water,psychic}     82.833333
{water,rock}        89.200000
{water,steel}       86.000000
{water}             69.500000
Name: attack, Length: 203, dtype: float64
type
{bug,dark}          92
{bug,electric}     108
{bug,fairy}        124
{bug,fighting}     151
{bug,fire}         100
                  ... 
{water,poison}     100
{water,psychic}    115
{water,rock}        74
{water,steel}       60
{water}            136
Name: speed, Length: 203, dtype: int64


In [24]:
# Sort pokemon by Attack (Descending)
df_sorted = df.sort_values(by="attack", ascending=False)
print(df_sorted)
# Sort by Multiple Columns (Sort by Attack, then Speed)
df_sorted = df.sort_values(by=["attack", "speed"], ascending=[False, True])
print(df_sorted)

      id       name  height  weight   hp  attack  defense  s_attack  \
797  798    kartana       3       1   59     181      131        59   
408  409  rampardos      16    1025   97     165       60        65   
288  289    slaking      20    1305  150     160      100        95   
485  486  regigigas      37    4200  110     160      110        80   
643  644     zekrom      29    3450  100     150      120       120   
..   ...        ...     ...     ...  ...     ...      ...       ...   
241  242    blissey      15     468  255      10       10        75   
128  129   magikarp       9     100   20      10       55        15   
212  213    shuckle       6     205   20      10      230        10   
439  440    happiny       6     244  100       5        5        15   
112  113    chansey      11     346  250       5        5        35   

     s_defense  speed               type  evo_set  \
797         31    109      {grass,steel}      419   
408         50     58             {rock} 

In [25]:
# Apply a function to an entire column
df["speed_modified"] = df["speed"].apply(lambda x: x * 1.5 if x > 80 else x)

# Apply function to multiple columns (Row-wise)
df["power_score"] = df.apply(lambda row: row["attack"] + row["speed"], axis=1)
print(df["speed_modified"])
print(df["power_score"])


0        45.0
1        60.0
2        80.0
3        65.0
4        80.0
        ...  
1020     75.0
1021    186.0
1022    147.0
1023     60.0
1024    132.0
Name: speed_modified, Length: 1025, dtype: float64
0        94
1       122
2       162
3       117
4       144
       ... 
1020    148
1021    244
1022    170
1023    125
1024    176
Name: power_score, Length: 1025, dtype: int64


In [26]:
# Checking for missing values
print("\n Missing Values in Dataset:")
print(df.isnull().sum())

# Filling missing Attack values with Mean
df["attack"] = df["attack"].fillna(df["attack"].mean())
print("\n Filling Missing Attack Values with Mean:")
print(df[["name", "attack"]].head())



 Missing Values in Dataset:
id                 0
name               0
height             0
weight             0
hp                 0
attack             0
defense            0
s_attack           0
s_defense          0
speed              0
type               0
evo_set            0
info               0
attack_boosted     0
speed_halved       0
attack_modified    0
speed_rank         0
total_stats        0
speed_modified     0
power_score        0
dtype: int64

 Filling Missing Attack Values with Mean:
         name  attack
0   bulbasaur      49
1     ivysaur      62
2    venusaur      82
3  charmander      52
4  charmeleon      64


In [27]:
# Creating extra DataFrame for merging
extra_data = pd.DataFrame({
    "name": df["name"].head(),  # Take first few pokemon names
    "legendary": [False, False, True, False, True]  # Random legendary status
})

# Merging on 'name' column
df_merged = df.merge(extra_data, on="name", how="left")
print("\n🔹 Merging with Extra Data (Legendary Status):")
print(df_merged.head())



🔹 Merging with Extra Data (Legendary Status):
   id        name  height  weight  hp  attack  defense  s_attack  s_defense  \
0   1   bulbasaur       7      69  45      49       49        65         65   
1   2     ivysaur      10     130  60      62       63        80         80   
2   3    venusaur      20    1000  80      82       83       100        100   
3   4  charmander       6      85  39      52       43        60         50   
4   5  charmeleon      11     190  58      64       58        80         65   

   speed  ... evo_set                                               info  \
0     45  ...       1  A strange seed was planted on its back at birt...   
1     60  ...       1  When the bulb on its back grows large, it appe...   
2     80  ...       1  The plant blooms when it is absorbing solar en...   
3     65  ...       2  Obviously prefers hot places. When it rains, s...   
4     80  ...       2  When it swings its burning tail, it elevates t...   

  attack_boosted  spe

# Combining Datasets: 
1. Concatenation
2. Merging
3. Joins
4. Aggregation and Grouping
5. Pivot Tables


In [28]:
import pandas as pd
# Concatenation: 
# Create a small dataset with new pokemon
new_pokemon = pd.DataFrame({
    "name": ["Newpokemon1", "NewPokemon2"],
    "type_1": ["Electric", "Grass"],
    "hp": [35, 45],
    "attack": [55, 49]
})

# Concatenate vertically (Adding rows)
df_combined = pd.concat([df, new_pokemon], ignore_index=True)
print(df_combined.tail())


          id         name  height  weight  hp  attack  defense  s_attack  \
1022  1023.0   iron-crown    16.0  1560.0  90      72    100.0     122.0   
1023  1024.0    terapagos     2.0    65.0  90      65     85.0      65.0   
1024  1025.0    pecharunt     3.0     3.0  88      88    160.0      88.0   
1025     NaN  Newpokemon1     NaN     NaN  35      55      NaN       NaN   
1026     NaN  NewPokemon2     NaN     NaN  45      49      NaN       NaN   

      s_defense  speed  ... evo_set  \
1022      108.0   98.0  ...   546.0   
1023       85.0   60.0  ...   548.0   
1024       88.0   88.0  ...   549.0   
1025        NaN    NaN  ...     NaN   
1026        NaN    NaN  ...     NaN   

                                                   info attack_boosted  \
1022  It resembles a mysterious object introduced in...           82.0   
1023  Terapagos protects itself using its power to t...           75.0   
1024  It feeds others toxic mochi that draw out desi...           98.0   
1025        

In [29]:
#Merging: 
# Example evolution dataset
evolution_data = pd.DataFrame({
    "name": ["Bulbasaur", "Charmander", "Squirtle"],
    "evolves_to": ["Ivysaur", "Charmeleon", "Wartortle"]
})

# Merge on "name" column (Default: INNER JOIN)
df_merged = pd.merge(df, evolution_data, on="name", how="left")
print(df_merged.head())


   id        name  height  weight  hp  attack  defense  s_attack  s_defense  \
0   1   bulbasaur       7      69  45      49       49        65         65   
1   2     ivysaur      10     130  60      62       63        80         80   
2   3    venusaur      20    1000  80      82       83       100        100   
3   4  charmander       6      85  39      52       43        60         50   
4   5  charmeleon      11     190  58      64       58        80         65   

   speed  ... evo_set                                               info  \
0     45  ...       1  A strange seed was planted on its back at birt...   
1     60  ...       1  When the bulb on its back grows large, it appe...   
2     80  ...       1  The plant blooms when it is absorbing solar en...   
3     65  ...       2  Obviously prefers hot places. When it rains, s...   
4     80  ...       2  When it swings its burning tail, it elevates t...   

  attack_boosted  speed_halved  attack_modified  speed_rank  total_s

In [30]:
import pandas as pd
# Joins: 
# pokemon stats dataset
df_stats = pd.DataFrame({
    "hp": [45, 60, 80],
    "attack": [49, 62, 82],
    "defense": [49, 63, 83]
}, index=["Bulbasaur", "Charmeleon", "Venusaur"])

# pokemon types dataset
df_types = pd.DataFrame({
    "type_1": ["Grass", "Fire", "Grass"],
    "type_2": ["Poison", None, "Poison"]
}, index=["Bulbasaur", "Charmeleon", "Venusaur"])

# Perform the join
df_joined = df_stats.join(df_types)
print("\n",df_joined)

# INNER JOIN (Only matching pokemon)
df_inner = df_stats.join(df_types, how="inner")
print("\n",df_inner)

# OUTER JOIN (Keeps all pokemon, fills missing values with NaN)
df_outer = df_stats.join(df_types, how="outer")
print("\n",df_outer)

# RIGHT JOIN (Keeps all pokemon from df_types)
df_right = df_stats.join(df_types, how="right")
print("\n",df_right)


             hp  attack  defense type_1  type_2
Bulbasaur   45      49       49  Grass  Poison
Charmeleon  60      62       63   Fire    None
Venusaur    80      82       83  Grass  Poison

             hp  attack  defense type_1  type_2
Bulbasaur   45      49       49  Grass  Poison
Charmeleon  60      62       63   Fire    None
Venusaur    80      82       83  Grass  Poison

             hp  attack  defense type_1  type_2
Bulbasaur   45      49       49  Grass  Poison
Charmeleon  60      62       63   Fire    None
Venusaur    80      82       83  Grass  Poison

             hp  attack  defense type_1  type_2
Bulbasaur   45      49       49  Grass  Poison
Charmeleon  60      62       63   Fire    None
Venusaur    80      82       83  Grass  Poison


In [31]:
import pandas as pd

# Aggregating pokemon stats
print("Total HP:", df["hp"].sum())      # Sum of all HPs
print("Average Attack:", df["attack"].mean())  # Mean attack
print("Strongest pokemon (Attack):", df["attack"].max())  # Max attack
print("Weakest pokemon (Defense):", df["defense"].min())  # Min defense
print("Total pokemon:", df["name"].count())  # Total count


Total HP: 71939
Average Attack: 77.52195121951219
Strongest pokemon (Attack): 181
Weakest pokemon (Defense): 5
Total pokemon: 1025


In [32]:
# Group-By: 
# Group pokemon by Type and Get Stats
type_stats = df.groupby("name")[["attack", "hp", "defense"]].agg(["min", "max", "mean"])
print("\n",type_stats)



           attack               hp             defense            
             min  max   mean  min  max   mean     min  max   mean
name                                                             
abomasnow     92   92   92.0   90   90   90.0      75   75   75.0
abra          20   20   20.0   25   25   25.0      15   15   15.0
absol        130  130  130.0   65   65   65.0      60   60   60.0
accelgor      70   70   70.0   80   80   80.0      40   40   40.0
aegislash     50   50   50.0   60   60   60.0     140  140  140.0
...          ...  ...    ...  ...  ...    ...     ...  ...    ...
zoroark      105  105  105.0   60   60   60.0      60   60   60.0
zorua         65   65   65.0   40   40   40.0      40   40   40.0
zubat         45   45   45.0   40   40   40.0      35   35   35.0
zweilous      85   85   85.0   72   72   72.0      70   70   70.0
zygarde      100  100  100.0  108  108  108.0     121  121  121.0

[1025 rows x 9 columns]


In [33]:
#GroupBy - Count pokemon per Group
type_counts = df.groupby("attack")["name"].count()
print("\n",type_counts)



 attack
5       2
10      3
15      1
20     10
22      1
       ..
147     1
150     4
160     2
165     1
181     1
Name: name, Length: 117, dtype: int64


In [34]:
#GroupBy - Find the Strongest pokemon per Type
strongest_per_type = df.loc[df.groupby("type")["attack"].idxmax(), ["name", "attack"]]
print(strongest_per_type)


          name  attack
919      lokix     102
736  charjabug      82
742   ribombee      55
793   buzzwole     139
635   larvesta      85
..         ...     ...
210   qwilfish      95
778    bruxish     105
833    drednaw     115
394   empoleon      86
98     kingler     130

[203 rows x 2 columns]


In [35]:
#GroupBy - Average HP per type
print(df.groupby("type")["hp"].mean())

type
{bug,dark}         71.000000
{bug,electric}     63.500000
{bug,fairy}        50.000000
{bug,fighting}     85.750000
{bug,fire}         70.000000
                     ...    
{water,poison}     61.666667
{water,psychic}    83.000000
{water,rock}       76.600000
{water,steel}      84.000000
{water}            64.891892
Name: hp, Length: 203, dtype: float64


In [36]:
#Pivot tables:
#Average Attack per pokemon Type
pivot_table = df.pivot_table(values="attack", index="type", aggfunc="mean")
print(pivot_table)


                     attack
type                       
{bug,dark}       102.000000
{bug,electric}    69.000000
{bug,fairy}       50.000000
{bug,fighting}   134.000000
{bug,fire}        72.500000
...                     ...
{water,poison}    68.333333
{water,psychic}   82.833333
{water,rock}      89.200000
{water,steel}     86.000000
{water}           69.500000

[203 rows x 1 columns]


In [37]:
# Pivot Table with Multiple Aggregations (Min, Max, Mean Attack)
pivot_table = df.pivot_table(values="attack", index="type", aggfunc=["min", "max", "mean"])
print(pivot_table)


                   min    max        mean
                attack attack      attack
type                                     
{bug,dark}         102    102  102.000000
{bug,electric}      47     82   69.000000
{bug,fairy}         45     55   50.000000
{bug,fighting}     125    139  134.000000
{bug,fire}          60     85   72.500000
...                ...    ...         ...
{water,poison}      40     95   68.333333
{water,psychic}     65    105   82.833333
{water,rock}        55    115   89.200000
{water,steel}       86     86   86.000000
{water}             10    130   69.500000

[203 rows x 3 columns]


In [38]:
#Counting pokemon per Type (Using Pivot Table)
pivot_table = df.pivot_table(values="name", index="type", aggfunc="count")
print(pivot_table)


                 name
type                 
{bug,dark}          1
{bug,electric}      4
{bug,fairy}         2
{bug,fighting}      4
{bug,fire}          2
...               ...
{water,poison}      3
{water,psychic}     6
{water,rock}        5
{water,steel}       1
{water}            74

[203 rows x 1 columns]
